name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 올린 파일들 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        run: echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP 사용 EC2에 빌드된 파일 전송
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /backend-server/tobe

      - name: SSH 사용하여 EC2 접속 및 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          # EC2의 주소
          host: ${{ secrets.EC2_HOST }}
          # EC2 접속 username
          username: ${{ secrets.EC2_USERNAME }}
          # EC2의 Key 파일
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true # 실패하면 전체 실패 처리
          script: |
            # 이전 폴더 삭제
            rm -rf /backend-server/current
            
            # 폴더 다시 생성 
            mkdir /backend-server/current
            
            # tobe -> current 빌드파일 이동 
            mv /backend-server/tobe/project.jar /backend-server/current/project.jar
            
            cd /backend-server/current
            
            # 실행 중인 애플리케이션 종료 (서버가 실행 중이 아니어도 에러 없이 통과)
            sudo fuser -k -n tcp 8080 || true
            
            # 종료 대기 (3초)
            sleep 3
            
            # 애플리케이션 실행 output.log 로그 기록 
            nohup java -jar project.jar > ./output.log 2>&1 &
            
            # 폴더 삭제 
            rm -rf /backend-server/tobe
            
            # 배포 완료
